[fix] コードが折り返されない不具合を修正
fixmix-hackathon/fixmix_frontend pull request #11
Opened 2023-09-06 14:39 UTC by TatsuruHisanaga

## 変更の概要
`hilight.js`によるコードのシンタックスハイライトが折り返されず、１行のコードが長い場合に意図した要素からはみ出されてしまう不具合を修正しました。
#8 #9

変更後の画像：
![image](https://github.com/fixmix-hackathon/fixmix_frontend/assets/119847001/dff4884c-eac0-4cba-a462-2b3fa090080d)

> この変更により、コードの折り返しが有効になりました。（画像の青い選択部分）

## なぜこの変更をするのか
コードが折り返されなかった場合、コンテンツ全体の横幅が画面幅よりも広くなってしまうため、該当するメッセージを消去しない限りはUIが永続的に崩れてしまう問題がありました。

## やったこと

-  新たに`CodeBlock.module.css`ファイルを作成し、デフォルトでコードの折り返しが適用されるようにスタイルを追加した。
- うまく適用できていなかったスタイルを消去した。
- famの画像幅を`auto`にし、画面幅が小さくなっても優先的に表示され続けるようにした。
- `marked`ライブラリのオプション`langPrefix`を追加した。

`langPrefix` は、`marked` ライブラリのオプションの一つで、生成されるコードブロックの`<code>`タグに適用されるCSSクラスのプレフィックスを定義します。

例えば、Markdownファイルに以下のようなコードブロックがあるとします：

```markdown
```javascript
console.log('Hello, World!');
```

`marked` がこれをHTMLに変換するとき、`langPrefix` オプションが `'language-'` に設定されていると、生成されるHTMLは以下のようになります：

```html
<pre>
  <code class="language-javascript">
    console.log('Hello, World!');
  </code>
</pre>
```

この `language-javascript` クラスは、シンタックスハイライトライブラリ（例：Prism.jsやHighlight.js）がJavaScriptコードとしてこのブロックをハイライトするために使用します。

このプレフィックスを変更すると、生成されるHTMLのクラス名も変わります。これは、特定のCSSスタイルを適用する場合や、異なるシンタックスハイライトライブラリを使用する場合に便利です。

今回の変更では`langPrefix`の追加はUIに影響しませんが、今後のことを考えて導入してみました。

2023-09-07 05:38 UTC, KO1231 requested changes
コードの折返しが確認できませんでした。
また、一部環境(reviewer確認でiOS)においてfαmアイコンの描画に不具合を確認しました。
（詳細はコメント）

2023-09-07 05:38 UTC, KO1231 commented on app/components/CodeBlock.module.css
> +.markdown pre, .markdown code {
### **master**
![image](https://github.com/fixmix-hackathon/fixmix_frontend/assets/124903312/22d5eb71-ff22-4977-8e2c-cb6c8496b0e3)

### **develop**
![image](https://github.com/fixmix-hackathon/fixmix_frontend/assets/124903312/d8a456eb-c82d-4f3a-9328-58f6d2be2104)

と1行あたり長いコードを無理やり出力させたとき、折り返されるのを確認できませんでした。

2023-09-07 05:38 UTC, KO1231 commented on app/components/Chat.tsx
> -                    w="45px"
### **master**
![image](https://github.com/fixmix-hackathon/fixmix_frontend/assets/124903312/c054cc09-c9c5-45bb-bcec-8ff3ffe1da94)

### **develop**
![image](https://github.com/fixmix-hackathon/fixmix_frontend/assets/124903312/8cc7c112-26f0-4db9-97f3-e35afd795d46)

と手持ちのiOS環境でfαmの描画が切れている状態になっています。
環境としては、iPhone 14 Plus (iOS 16.6, Safari 16.6) 、iPhone 7 Plus(iOS 15.7.5,  Safari 15.6.4)です。
なお、Android環境、Windows環境(ともにGoogle Chrome)では特に描画切れ等確認できなかったので、Safari特有等一部環境で見られるものの可能性があります。

2023-09-07 05:38 UTC, KO1231 commented on app/components/Chat.tsx
> -                        }}
### **master**
![image](https://github.com/fixmix-hackathon/fixmix_frontend/assets/124903312/c054cc09-c9c5-45bb-bcec-8ff3ffe1da94)

### **develop**
![image](https://github.com/fixmix-hackathon/fixmix_frontend/assets/124903312/8cc7c112-26f0-4db9-97f3-e35afd795d46)

whiteSpace: 'pre-wrap' が適用されていないようです。class化したときの適用がうまくいっていない可能性があります。

2023-09-09 13:54 UTC, TatsuruHisanaga commented
@KO1231 
一応修正できそうなんやけども、これって別のプルリク出したらまずいんかな😅
このプルリク内で新しくマージのレビューとかできるん？

2023-09-10 10:38 UTC, KO1231 approved these changes

2023-09-10 10:49 UTC, merged